//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProduktyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketItems
    {
        public int BasketId { get; set; }
        public int BasketIdFOREIGN { get; set; }
        public int BasketItemId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Products_TEST Products_TEST { get; set; }
    }
}
