//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProduktyService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_TEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_TEST()
        {
            this.BasketItems = new HashSet<BasketItems>();
        }
    
        public int ProdID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int SubID { get; set; }
        public int ManID { get; set; }
        public string Model { get; set; }
        public string Specification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketItems> BasketItems { get; set; }
    }

    public class Products
    {
        public int ProdID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Specification { get; set; }
    }
}
